"""
Job submission endpoints.

Two submission modes
---------------------
POST /api/v1/jobs/upload
    Laravel uploads image files directly to this service.  The service
    saves them under LM2_UPLOAD_DIR/<job_id>/ and starts processing.
    This is the recommended mode when the servers are separate.

POST /api/v1/jobs
    Laravel pre-transfers files to LM2_UPLOAD_DIR/<job_id>/ by another
    means (e.g. SFTP, shared NFS) and then notifies this service to start.
    The body carries job_id, run_name, and optional config_overrides.

GET /api/v1/jobs/{job_id}/results/{filename}
    Streams a single result file (CSV/JSON/PNG/PDF) back to the caller.
    Primarily used when Laravel needs to pull a file from this service.
    Path traversal is blocked — the resolved path must stay inside
    LM2_OUTPUT_DIR/<job_id>/.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

from fastapi import (
    APIRouter,
    BackgroundTasks,
    File,
    Form,
    HTTPException,
    UploadFile,
    status,
)
from fastapi.responses import FileResponse

from api.config import settings
from api.runner import run_job, validate_config_overrides
from api.schemas import JobAccepted, JobRequest

logger = logging.getLogger("lm2.routers.jobs")

router = APIRouter(
    prefix="/api/v1/jobs",
    tags=["jobs"],
)


# ── Path helpers ──────────────────────────────────────────────────────────────

def _resolve_upload_dir(job_id: str) -> Path:
    """Return the upload directory for a job, guaranteed within LM2_UPLOAD_DIR."""
    base = Path(settings.LM2_UPLOAD_DIR).resolve()
    target = (base / job_id).resolve()
    if not target.is_relative_to(base):
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Invalid job_id path segment")
    return target


def _resolve_output_file(job_id: str, filename: str) -> Path:
    """Resolve a result file path, guaranteeing it stays within LM2_OUTPUT_DIR/<job_id>.

    Raises HTTP 400 on path traversal attempts, HTTP 404 if file does not exist.
    """
    base = (Path(settings.LM2_OUTPUT_DIR) / job_id).resolve()
    # Strip any leading separators from the caller-supplied filename so that
    # Path joining cannot escape the base directory.
    safe_filename = filename.lstrip("/\\")
    target = (base / safe_filename).resolve()
    if not target.is_relative_to(base):
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Path traversal detected")
    if not target.is_file():
        raise HTTPException(status.HTTP_404_NOT_FOUND, f"Result file '{filename}' not found")
    return target


def _parse_config_overrides(raw: str | None) -> dict:
    """Parse and validate the JSON config_overrides field from a form submission."""
    if not raw:
        return {}
    try:
        overrides = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_ENTITY,
            f"config_overrides is not valid JSON: {exc}",
        )
    if not isinstance(overrides, dict):
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_ENTITY,
            "config_overrides must be a JSON object",
        )
    try:
        validate_config_overrides(overrides)
    except ValueError as exc:
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_ENTITY, str(exc))
    return overrides


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.post(
    "/upload",
    status_code=status.HTTP_202_ACCEPTED,
    response_model=JobAccepted,
    summary="Upload images and start a job (recommended for cross-server deployments)",
)
async def upload_and_run(
    background_tasks: BackgroundTasks,
    job_id: str = Form(..., description="UUID generated by Laravel for this job"),
    run_name: str = Form(..., description="Human-readable run identifier"),
    files: list[UploadFile] = File(..., description="Image files to process"),
    config_overrides: str | None = Form(
        default=None,
        description="Optional JSON object with LeafMachine2 config overrides. "
        "Blocked keys: dir_images_local, dir_output, run_name, dir_home.",
    ),
) -> JobAccepted:
    """Receive image files from Laravel, save them, and start the pipeline.

    Returns 202 Accepted immediately.  Progress and final status are pushed
    back to Laravel via the configured callback URL.
    """
    # Validate job_id (alphanumeric + hyphens/underscores, max 128)
    import re
    if not re.fullmatch(r"[\w\-]{1,128}", job_id):
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_ENTITY,
            "job_id must contain only alphanumeric characters, hyphens, or underscores",
        )

    overrides = _parse_config_overrides(config_overrides)
    upload_dir = _resolve_upload_dir(job_id)
    upload_dir.mkdir(parents=True, exist_ok=True)

    # Save uploaded files — strip directory components from filenames to
    # prevent callers from writing outside upload_dir.
    for file in files:
        safe_name = Path(file.filename).name if file.filename else file.filename
        if not safe_name:
            raise HTTPException(
                status.HTTP_422_UNPROCESSABLE_ENTITY, "One or more uploaded files has no filename"
            )
        dest = upload_dir / safe_name
        contents = await file.read()
        dest.write_bytes(contents)
        logger.debug("Saved upload %s -> %s", safe_name, dest)

    background_tasks.add_task(
        run_job,
        job_id=job_id,
        input_dir=str(upload_dir),
        run_name=run_name,
        config_overrides=overrides,
    )

    logger.info("Job %s enqueued (%d files, run_name=%s)", job_id, len(files), run_name)
    return JobAccepted(job_id=job_id)


@router.post(
    "",
    status_code=status.HTTP_202_ACCEPTED,
    response_model=JobAccepted,
    summary="Start a job for pre-transferred files (shared storage / SFTP mode)",
)
def submit_job(
    body: JobRequest,
    background_tasks: BackgroundTasks,
) -> JobAccepted:
    """Start processing files that Laravel has already transferred to the server.

    The files must exist under LM2_UPLOAD_DIR/<job_id>/ before this endpoint
    is called.  Returns 202 Accepted immediately.
    """
    upload_dir = _resolve_upload_dir(body.job_id)
    if not upload_dir.exists():
        raise HTTPException(
            status.HTTP_404_NOT_FOUND,
            f"Upload directory for job '{body.job_id}' does not exist. "
            "Transfer files before submitting the job.",
        )

    try:
        validate_config_overrides(body.config_overrides)
    except ValueError as exc:
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_ENTITY, str(exc))

    background_tasks.add_task(
        run_job,
        job_id=body.job_id,
        input_dir=str(upload_dir),
        run_name=body.run_name,
        config_overrides=body.config_overrides,
    )

    logger.info("Job %s enqueued (pre-transferred files, run_name=%s)", body.job_id, body.run_name)
    return JobAccepted(job_id=body.job_id)


@router.get(
    "/{job_id}/results/{filename:path}",
    summary="Download a single result file",
    response_class=FileResponse,
)
def download_result(job_id: str, filename: str) -> FileResponse:
    """Stream a result file (CSV, JSON, PNG, PDF) to the caller.

    ``filename`` may include subdirectory segments (e.g. ``overlays/img1.png``).
    Path traversal attempts (``../``, absolute paths) are rejected with 400.
    """
    # Validate job_id before using it in path construction
    import re
    if not re.fullmatch(r"[\w\-]{1,128}", job_id):
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Invalid job_id")

    target = _resolve_output_file(job_id, filename)
    return FileResponse(path=str(target), filename=target.name)
